Attribute VB_Name = "modViewKit"
Option Explicit

    Public Const MIN_WIDTH = 8976
    Public Const MIN_HEIGHT = 6732

    Public Const SCT_KEEP_LEFT = &H1
    Public Const SCT_KEEP_TOP = &H2
    Public Const SCT_KEEP_RIGHT = &H4
    Public Const SCT_KEEP_BOTTOM = &H8
    Public Const SCT_KEEP_WIDTH = &H10
    Public Const SCT_KEEP_HEIGHT = &H20
    Public Const SCT_KEEP_LEFT_TOP = SCT_KEEP_LEFT + SCT_KEEP_TOP
    Public Const SCT_KEEP_RIGHT_TOP = SCT_KEEP_TOP + SCT_KEEP_RIGHT
    Public Const SCT_KEEP_LEFT_BOTTOM = SCT_KEEP_LEFT + SCT_KEEP_BOTTOM
    Public Const SCT_KEEP_RIGHT_BOTTOM = SCT_KEEP_RIGHT + SCT_KEEP_BOTTOM
    Public Const SCT_KEEP_LEFT_RIGHT = SCT_KEEP_LEFT + SCT_KEEP_RIGHT
    Public Const SCT_KEEP_TOP_BOTTOM = SCT_KEEP_TOP + SCT_KEEP_BOTTOM
    Public Const SCT_KEEP_BOTH = SCT_KEEP_WIDTH + SCT_KEEP_HEIGHT
    Public Const SCT_KEEP_SIZE = SCT_KEEP_BOTH
    Public Const SCT_SCALE = 0
    
    Public Const SCT_KEEP_ALL = SCT_KEEP_LEFT + SCT_KEEP_TOP + SCT_KEEP_RIGHT + SCT_KEEP_BOTTOM
    
    Public Const SCT_SIZE_LATERAL = 16
    Public Const SCT_SIZE_VERTICAL = 32

    Public Const SCT_ALEFT_SLATERAL = SCT_KEEP_LEFT + SCT_SIZE_LATERAL
    Public Const SCT_ARIGHT_SLATERAL = SCT_KEEP_RIGHT + SCT_SIZE_LATERAL
    Public Const SCT_ATOP_SVERTICAL = SCT_KEEP_TOP + SCT_SIZE_VERTICAL
    Public Const SCT_ABOTTOM_SVERTICAL = SCT_KEEP_BOTTOM + SCT_SIZE_VERTICAL
    Public Const SCT_ALEFTTOP_SLATERAL = SCT_KEEP_LEFT_TOP + SCT_SIZE_LATERAL
    Public Const SCT_ARIGHTTOP_SLATERAL = SCT_KEEP_RIGHT_TOP + SCT_SIZE_LATERAL
    Public Const SCT_ALEFTBOTTOM_SLATERAL = SCT_KEEP_LEFT_BOTTOM + SCT_SIZE_LATERAL
    Public Const SCT_ARIGHTBOTTOM_SLATERAL = SCT_KEEP_LEFT_BOTTOM + SCT_SIZE_LATERAL
    Public Const SCT_ALEFTTOP_SVERTICAL = SCT_KEEP_LEFT_TOP + SCT_SIZE_VERTICAL
    Public Const SCT_ARIGHTTOP_SVERTICAL = SCT_KEEP_RIGHT_TOP + SCT_SIZE_VERTICAL
    Public Const SCT_ALEFTBOTTOM_SVERTICAL = SCT_KEEP_LEFT_BOTTOM + SCT_SIZE_VERTICAL
    Public Const SCT_ARIGHTBOTTOM_SVERTICAL = SCT_KEEP_LEFT_BOTTOM + SCT_SIZE_VERTICAL

