rem Assume: current directory is \release\exectrak\setup

@echo off
deltree /Y .\disk\disk1
md .\disk\disk1
copy diskid.bat .\disk\disk1\disk1.id

deltree /Y .\disk\disk2
md .\disk\disk2
copy diskid.bat .\disk\disk2\disk2.id

deltree /Y .\disk\disk3
md .\disk\disk3
copy diskid.bat .\disk\disk3\disk3.id

deltree /Y .\disk\disk4
md .\disk\disk4
copy diskid.bat .\disk\disk4\disk4.id

deltree /Y .\disk\disk5
md .\disk\disk5
copy diskid.bat .\disk\disk5\disk5.id

deltree /Y .\disk\disk6
md .\disk\disk6
copy diskid.bat .\disk\disk6\disk6.id

deltree /Y .\disk\disk7
md .\disk\disk7
copy diskid.bat .\disk\disk7\disk7.id

deltree /Y .\disk\disk8
md .\disk\disk8
copy diskid.bat .\disk\disk8\disk8.id

deltree /Y .\disk\disk9
md .\disk\disk9
copy diskid.bat .\disk\disk9\disk9.id

deltree /Y .\disk\disk10
md .\disk\disk10
copy diskid.bat .\disk\disk10\disk10.id

deltree /Y .\disk\disk11
md .\disk\disk11
copy diskid.bat .\disk\disk11\disk11.id

deltree /Y .\disk\disk12
md .\disk\disk12
copy diskid.bat .\disk\disk12\disk12.id

deltree /Y .\disk\disk13
md .\disk\disk13
copy diskid.bat .\disk\disk13\disk13.id

deltree /Y .\disk\disk14
md .\disk\disk14
copy diskid.bat .\disk\disk14\disk14.id

deltree /Y .\disk\disk15
md .\disk\disk15
copy diskid.bat .\disk\disk15\disk15.id

deltree /Y .\disk\disk16
md .\disk\disk16
copy diskid.bat .\disk\disk16\disk16.id

deltree /Y .\disk\disk17
md .\disk\disk17
copy diskid.bat .\disk\disk17\disk17.id

deltree /Y .\disk\disk18
md .\disk\disk18
copy diskid.bat .\disk\disk18\disk18.id

deltree /Y .\disk\disk19
md .\disk\disk19
copy diskid.bat .\disk\disk19\disk19.id

deltree /Y .\disk\disk20
md .\disk\disk20
copy diskid.bat .\disk\disk20\disk20.id
