@echo off
deltree /Y ..\disk\disk1
md ..\disk\disk1
copy disk.id ..\disk\disk1\disk1.id

deltree /Y ..\disk\disk2
md ..\disk\disk2
copy disk.id ..\disk\disk2\disk2.id

deltree /Y ..\disk\disk3
md ..\disk\disk3
copy disk.id ..\disk\disk3\disk3.id

deltree /Y ..\disk\disk4
md ..\disk\disk4
copy disk.id ..\disk\disk4\disk4.id

deltree /Y ..\disk\disk5
md ..\disk\disk5
copy disk.id ..\disk\disk5\disk5.id

deltree /Y ..\disk\disk6
md ..\disk\disk6
copy disk.id ..\disk\disk6\disk6.id

deltree /Y ..\disk\disk7
md ..\disk\disk7
copy disk.id ..\disk\disk7\disk7.id

deltree /Y ..\disk\disk8
md ..\disk\disk8
copy disk.id ..\disk\disk8\disk8.id

deltree /Y ..\disk\disk9
md ..\disk\disk9
copy disk.id ..\disk\disk9\disk9.id

deltree /Y ..\disk\disk10
md ..\disk\disk10
copy disk.id ..\disk\disk10\disk10.id

deltree /Y ..\disk\disk11
md ..\disk\disk11
copy disk.id ..\disk\disk11\disk11.id

deltree /Y ..\disk\disk12
md ..\disk\disk12
copy disk.id ..\disk\disk12\disk12.id

deltree /Y ..\disk\disk13
md ..\disk\disk13
copy disk.id ..\disk\disk13\disk13.id

deltree /Y ..\disk\disk14
md ..\disk\disk14
copy disk.id ..\disk\disk14\disk14.id
