@echo off
deltree /Y ..\disk\disk1
md ..\disk\disk1
copy disk.id ..\disk\disk1\disk1.id

deltree /Y ..\disk\disk2
md ..\disk\disk2
copy disk.id ..\disk\disk2\disk2.id

deltree /Y ..\disk\disk3
md ..\disk\disk3
copy disk.id ..\disk\disk3\disk3.id

deltree /Y ..\disk\disk4
md ..\disk\disk4
copy disk.id ..\disk\disk4\disk4.id

deltree /Y ..\disk\disk5
md ..\disk\disk5
copy disk.id ..\disk\disk5\disk5.id

deltree /Y ..\disk\disk6
md ..\disk\disk6
copy disk.id ..\disk\disk6\disk6.id

deltree /Y ..\disk\disk7
md ..\disk\disk7
copy disk.id ..\disk\disk7\disk7.id

deltree /Y ..\disk\disk8
md ..\disk\disk8
copy disk.id ..\disk\disk8\disk8.id

deltree /Y ..\disk\disk9
md ..\disk\disk9
copy disk.id ..\disk\disk9\disk9.id

deltree /Y ..\disk\disk10
md ..\disk\disk10
copy disk.id ..\disk\disk10\disk10.id

deltree /Y ..\disk\disk11
md ..\disk\disk11
copy disk.id ..\disk\disk11\disk11.id

deltree /Y ..\disk\disk12
md ..\disk\disk12
copy disk.id ..\disk\disk12\disk12.id

deltree /Y ..\disk\disk13
md ..\disk\disk13
copy disk.id ..\disk\disk13\disk13.id

deltree /Y ..\disk\disk14
md ..\disk\disk14
copy disk.id ..\disk\disk14\disk14.id

deltree /Y ..\disk\disk15
md ..\disk\disk15
copy disk.id ..\disk\disk15\disk15.id

deltree /Y ..\disk\disk16
md ..\disk\disk16
copy disk.id ..\disk\disk16\disk16.id

deltree /Y ..\disk\disk17
md ..\disk\disk17
copy disk.id ..\disk\disk17\disk17.id

deltree /Y ..\disk\disk18
md ..\disk\disk18
copy disk.id ..\disk\disk18\disk18.id

deltree /Y ..\disk\disk19
md ..\disk\disk19
copy disk.id ..\disk\disk19\disk19.id

deltree /Y ..\disk\disk20
md ..\disk\disk20
copy disk.id ..\disk\disk20\disk20.id

deltree /Y ..\disk\disk21
md ..\disk\disk21
copy disk.id ..\disk\disk21\disk21.id

deltree /Y ..\disk\disk22
md ..\disk\disk22
copy disk.id ..\disk\disk22\disk22.id

deltree /Y ..\disk\disk23
md ..\disk\disk23
copy disk.id ..\disk\disk23\disk23.id

deltree /Y ..\disk\disk24
md ..\disk\disk24
copy disk.id ..\disk\disk24\disk24.id

deltree /Y ..\disk\disk25
md ..\disk\disk25
copy disk.id ..\disk\disk25\disk25.id

deltree /Y ..\disk\disk26
md ..\disk\disk26
copy disk.id ..\disk\disk26\disk26.id

deltree /Y ..\disk\disk27
md ..\disk\disk27
copy disk.id ..\disk\disk27\disk27.id

deltree /Y ..\disk\disk28
md ..\disk\disk28
copy disk.id ..\disk\disk28\disk28.id

deltree /Y ..\disk\disk29
md ..\disk\disk29
copy disk.id ..\disk\disk29\disk29.id

deltree /Y ..\disk\disk30
md ..\disk\disk30
copy disk.id ..\disk\disk30\disk30.id